Repository elan-ev/studip-opencast-plugin, pull requests merged in 2023-10, with the labels that each got.

#808 Fix missing function error in studip action menu, fixes #807
  vueapp/components/Studip/StudipActionMenu.vue
Labels: type:bug, v:3

#805 Remove redundant global config option
  lib/Providers/OpencastConstants.php
Labels: type:bug, v:3

#810 Reload videos after upload
  vueapp/components/Videos/VideoUpload.vue
  vueapp/components/Videos/VideosList.vue
  vueapp/store/videos.module.js
Labels: type:bug, v:3, priority:high

#813 Filter existing videos when adding videos to playlist
  vueapp/components/Videos/VideosList.vue
Labels: type:bug, v:3

#817 Videos table
  assets/css/opencast.scss
  lib/Models/Filter.php
  vueapp/components/Playlists/PlaylistVideos.vue
  vueapp/components/SearchBar.vue
  vueapp/components/Videos/EmptyVideoCard.vue
  vueapp/components/Videos/EmptyVideoRow.vue
  vueapp/components/Videos/VideoRow.vue
  vueapp/components/Videos/VideosList.vue
  vueapp/components/Videos/VideosTable.vue
  vueapp/store/videos.module.js
  vueapp/views/CoursesVideos.vue
  vueapp/views/PlaylistEdit.vue
  vueapp/views/Videos.vue
  vueapp/views/VideosTrashed.vue
Labels: v:3, type:visual-clarity
