Repository elan-ev/studip-opencast-plugin, pull requests merged in 2023-08, with the labels that each got.

#732 Notify pull request authors about merge conflicts
  .github/workflows/check-merge-conflict.yml
Labels: type:infrastructure

#751 Multiple bug fixes
  lib/Routes/Playlist/PlaylistUpdate.php
  lib/Routes/Video/VideoCopyToCourse.php
  vueapp/components/Error.vue
  vueapp/components/SearchBar.vue
  vueapp/components/UserCourseSelectable.vue
  vueapp/components/Videos/Actions/CaptionUpload.vue
  vueapp/components/Videos/Actions/VideoAccess/ShareWithUsers.vue
  vueapp/components/Videos/Actions/VideoCopyToSeminar.vue
  vueapp/components/Videos/VideoCard.vue
  vueapp/components/Videos/VideoUpload.vue
  vueapp/components/Videos/VideosList.vue
  vueapp/store/playlists.module.js
Labels: type:bug, v:3

#743 scss restyling, better usability on small displays
  assets/css/opencast.scss
  vueapp/components/Config/EditServer.vue
  vueapp/components/PaginationButtons.vue
  vueapp/components/Playlists/PlaylistVideos.vue
  vueapp/components/UserPlaylistSelectable.vue
  vueapp/components/Videos/EmptyVideoCard.vue
  vueapp/components/Videos/VideoCard.vue
  vueapp/components/Videos/VideoUpload.vue
  vueapp/components/Videos/VideosList.vue
Labels: type:bug, v:3, type:usability, type:visual-clarity

#736 Show delete Button in subtitle dialog an fix playlist video counter
  vueapp/components/Videos/Actions/CaptionUpload.vue
  vueapp/store/playlists.module.js
Labels: type:bug, v:3

#735 Fix sql duplicate service_url error
  lib/Routes/Config/ConfigAddEdit.php
  migrations/074_update_config_key.php
Labels: type:bug, v:3

#752 Fix action menu for 4.6 - 5.3
  assets/css/opencast.scss
  migrations/053_add_default_config_option.php
  vueapp/components/Studip/StudipActionMenu.vue
Labels: type:bug, v:3

#754 fixes #688
  classes/OCRestClient/SchedulerClient.php
  controllers/course.php
  cronjobs/refresh_scheduled_events.php
  migrations/049_add_course_date_fields_for_events.php
  models/OCModel.php
Labels: type:bug, v:3, v:2

#766 Fixing server card issues
  lib/Models/Config.php
  lib/Models/Helpers.php
  lib/Routes/Config/ConfigAdd.php
  lib/Routes/Config/ConfigDelete.php
  lib/Routes/Config/ConfigEdit.php
  lib/Routes/Config/ConfigUpdate.php
  vueapp/components/Config/AdminConfigs.vue
  vueapp/components/Config/ConfigOption.vue
  vueapp/components/Config/GlobalOptions.vue
Labels: v:3, priority:low, type:usability

#775 Show pagination buttons only if usable #774
  vueapp/components/PaginationButtons.vue
Labels: type:bug, v:3
