Repository elan-ev/studip-opencast-plugin, pull requests merged in 2023-12, with the labels that each got.

#845 Drag-and-Drop for video sorting
  assets/css/opencast.scss
  assets/images/grabber_grey.svg
  vueapp/components/Videos/VideoRow.vue
  vueapp/components/Videos/VideosTable.vue
Labels: v:3, type:usability

#848 Playlists Changes
  assets/css/opencast.scss
  lib/Models/PlaylistSeminars.php
  lib/Models/Playlists.php
  lib/Models/Tags.php
  lib/Models/Videos.php
  lib/Routes/Course/CourseAddPlaylist.php
  lib/Routes/Course/CourseListForPlaylistVideos.php
  lib/Routes/Course/CourseListForUserVideos.php
  lib/Routes/Course/CourseListPlaylist.php
  lib/Routes/Playlist/PlaylistList.php
  vueapp/components/Courses/CoursesSidebar.vue
  vueapp/components/PaginationButtons.vue
  vueapp/components/Playlists/PlaylistAddCard.vue
  vueapp/components/Playlists/PlaylistAddNewCard.vue
  vueapp/components/Playlists/PlaylistAddVideos.vue
  vueapp/components/Playlists/PlaylistCard.vue
  vueapp/components/Playlists/PlaylistsLinkCard.vue
  vueapp/components/Playlists/PlaylistsTable.vue
  vueapp/components/SearchBar.vue
  vueapp/components/Videos/VideosTable.vue
  vueapp/store/playlists.module.js
  vueapp/store/videos.module.js
  vueapp/views/Playlists.vue
Labels: type:bug, v:3, type:feature

#853 Uniform messages for add video to playlist
  lib/Routes/Video/VideoAddToPlaylist.php
Labels: v:3, type:usability

#855 Use Studip-Icon for ServerCard checkbox and show incoming messages always as new ones
  vueapp/components/Config/ServerCard.vue
  vueapp/store/messages.module.js
Labels: v:3, type:visual-clarity

#859 Configurable list of upload file types
  lib/Models/Config.php
  lib/Models/Workflow.php
  lib/Routes/Config/SimpleConfigList.php
  migrations/082_add_workflow_settings.php
  vueapp/components/Config/EditServer.vue
  vueapp/components/Config/UploadOptions.vue
  vueapp/components/Videos/VideoUpload.vue
Labels: v:3, type:feature

#861 Hide video filters for courses and lecturers in course playlists
  vueapp/components/Videos/VideosTable.vue
Labels: v:3, type:usability

#856 Fehler bei leeren Inputs
  vueapp/components/Config/ConfigOption.vue
  vueapp/components/Config/EditServer.vue
  vueapp/components/Playlists/PlaylistAddNewCard.vue
  vueapp/components/Playlists/PlaylistEditCard.vue
  vueapp/components/Videos/Actions/VideoAccess/ShareWithUsers.vue
  vueapp/components/Videos/Actions/VideoEdit.vue
Labels: v:3, type:visual-clarity

#858 On missing series - hide upload and show warning
  vueapp/components/Courses/CoursesSidebar.vue
  vueapp/components/Videos/VideosSidebar.vue
  vueapp/store/config.module.js
  vueapp/store/opencast.module.js
  vueapp/views/Contents.vue
  vueapp/views/Course.vue
Labels: type:bug, v:3

#860 Instant save in VideoCopyToSeminar using studip-select
  vueapp/components/UserCourseSelectable.vue
  vueapp/components/Videos/Actions/VideoCopyToSeminar.vue
Labels: v:3, type:usability

#862 CW-Plugin: Highlight selected item, automatic search and lti fail message
  assets/css/courseware.scss
  courseware/vueapp/components/CoursewareSearchBar.vue
  courseware/vueapp/components/CoursewareVideoTable.vue
  courseware/vueapp/components/VideoRow.vue
  courseware/vueapp/courseware-plugin-opencast-video.vue
Labels: v:3, type:usability

#854 Messages for dialogs
  vueapp/components/Config/EditServer.vue
  vueapp/components/Config/ServerCard.vue
  vueapp/components/MessageList.vue
  vueapp/components/Playlists/PlaylistAddToCourseDialog.vue
  vueapp/components/Videos/Actions/CaptionUpload.vue
  vueapp/components/Videos/Actions/VideoAccess.vue
  vueapp/components/Videos/Actions/VideoLinkToPlaylists.vue
  vueapp/components/Videos/VideoUpload.vue
  vueapp/components/Videos/VideosTable.vue
  vueapp/store/messages.module.js
Labels: v:3, type:usability

#863 Add text on title for running video
  vueapp/components/Videos/VideoRow.vue
Labels: v:3, type:visual-clarity
