Repository elan-ev/studip-opencast-plugin, pull requests merged in 2023-11, with the labels that each got.

#818 Separate Spalte für den Video-Infoindikator
  vueapp/components/Videos/VideoRow.vue
  vueapp/components/Videos/VideosTable.vue
Labels: v:3, type:usability

#825 Prevent overflow of videos table on small devices
  assets/css/opencast.scss
Labels: type:mobile, v:3

#826 Show error messages on network errors
  vueapp/common/upload.service.js
  vueapp/components/Videos/Actions/CaptionUpload.vue
  vueapp/components/Videos/VideoUpload.vue
  vueapp/components/Videos/VideosTable.vue
  vueapp/store/error.module.js
  vueapp/store/opencast.module.js
Labels: type:bug, v:3, type:usability

#827 Fix some notification problems
  vueapp/components/MessageBox.vue
  vueapp/store/messages.module.js
  vueapp/store/playlists.module.js
Labels: type:bug, type:usability

#828 Clear errors when success message is displayed
  vueapp/store/messages.module.js
Labels: v:3, type:usability

#830 Search filter for courses and lecturers
  lib/Models/Filter.php
  lib/Models/PlaylistSeminars.php
  lib/Models/Videos.php
  lib/RouteMap.php
  lib/Routes/Course/CourseListForPlaylistVideos.php
  lib/Routes/Course/CourseListForUserVideos.php
  vueapp/components/SearchBar.vue
  vueapp/store/videos.module.js
Labels: type:enhancement

#840 Fix workflows save in server settings
  lib/Models/Config.php
Labels: type:bug, v:3

#838 Instant save in PlaylistAddToCourse and VideoLinkToPlaylists
  vueapp/components/Playlists/PlaylistAddToCourseDialog.vue
  vueapp/components/Videos/Actions/VideoAccess.vue
  vueapp/components/Videos/Actions/VideoAddToSeminar.vue
  vueapp/components/Videos/Actions/VideoLinkToPlaylists.vue
  vueapp/components/Videos/VideosTable.vue
  vueapp/store/playlists.module.js
  vueapp/store/videos.module.js
Labels: type:bug, v:3, type:usability

#841 Allow download of playlist separately for each course
  lib/Models/PlaylistSeminars.php
  lib/RouteMap.php
  lib/Routes/Course/CourseUpdatePlaylist.php
  migrations/079_add_allow_download_playlist_seminar.php
  vueapp/components/Courses/CoursesSidebar.vue
  vueapp/components/Videos/VideoRow.vue
  vueapp/store/playlists.module.js
Labels: v:3, type:feature

#842 Show number of new videos in my courses
  OpenCast.class.php
  app/controllers/course.php
  lib/Models/PlaylistVideos.php
  lib/Models/Videos.php
  migrations/079_add_playlist_video_dates.php
Labels: type:bug, v:3

#843 Warnings for Servercard and ability to disable configs
  cronjobs/opencast_discover_videos.php
  lib/Models/Helpers.php
  lib/Models/Videos.php
  lib/Routes/Config/ConfigEdit.php
  lib/Routes/Config/ConfigList.php
  lib/Routes/Config/SimpleConfigList.php
  migrations/079_add_config_active.php
  vueapp/components/Config/EditServer.vue
  vueapp/components/Config/GlobalOptions.vue
  vueapp/components/Config/ServerCard.vue
Labels: type:bug, v:3, type:usability

#844 Change icon for linking video and playlist
  vueapp/components/Playlists/PlaylistCard.vue
  vueapp/components/Videos/VideoRow.vue
Labels: v:3, type:visual-clarity
