Repository elan-ev/studip-opencast-plugin, pull requests merged in 2024-11, with the labels that each got.

#1047 Fix endless recursion in work place upload dialog
  vueapp/components/Videos/VideoUpload.vue
Labels: type:bug

#1069 Fix broken urls due to renaming
  courseware/vueapp/courseware-plugin-opencast-video.vue
  lib/Models/VideosUserPerms.php
  lib/Routes/Video/VideoSharesList.php
  vueapp/components/Courses/CoursesSidebar.vue
  vueapp/components/Playlists/PlaylistAddToCourseDialog.vue
  vueapp/components/Videos/Actions/VideoCopyToSeminar.vue
  vueapp/components/Videos/VideosSidebar.vue
Labels: type:bug

#1060 Remove anonymous role if video visibility is changed to internal
  lib/Models/Helpers.php
Labels: type:bug

#1058 Log php exceptions in slim routes
  lib/Errors/ExceptionHandler.php
Labels: type:bug

#1057 Fix null error if no default server exists
  lib/Routes/Config/ConfigList.php
Labels: type:bug, v:3

#1053 Fix views icon style
  assets/css/opencast.scss
Labels: type:bug

#1076 Fix courseware block
  courseware/vueapp/components/CoursewareVideoTable.vue
  courseware/vueapp/courseware-plugin-opencast-video.vue
Labels: type:bug, v:3

#1050 Disable page layout when loading the player
  app/controllers/redirect.php
  app/views/redirect/perform.php
Labels: v:3, type:visual-clarity

#1071 Do not update endpoints in cronjobs.
  lib/Models/Config.php
Labels: type:bug, v:3

#1075 Sync the latest events first in cronjob
  cronjobs/opencast_sync_acls.php
Labels: type:enhancement, v:3

#1077 Skip unavailable events in playlist migration
  lib/Helpers/PlaylistMigration.php
Labels: type:bug, v:3

#1078 Save correct service entry id in database
  lib/Models/Playlists.php
Labels: type:bug

#1048 Fix incorrect info in change course playlist dialog
  lib/Models/PlaylistSeminars.php
  lib/Models/Playlists.php
  lib/Routes/Playlist/PlaylistList.php
Labels: type:bug, v:3

#1054 Only touch ACLs managed by Stud.IP plugin
  classes/lti/OpencastLTI.php
Labels: type:bug, v:2

#1043 Fix incorrect playlist acl check
  lib/Models/Playlists.php
Labels: type:bug, v:3

#1084 Fix event acl cronjob
  lib/Models/Videos.php
Labels: type:bug, v:3

#1068 Filter legacy course acls
  lib/Models/Helpers.php
Labels: type:bug, v:3

#1079 Fix missing course acls in studio upload
  bootstrap.php
  bootstrap_migrations.php
  cronjobs/opencast_worker.php
Labels: type:bug

#1074 fixes #1034, prevent warning
  lib/Models/Videos.php
Labels: type:bug, v:3

#1089 Check edit permissions before allowing to add or remove playlists fro…
  lib/Routes/Course/CourseAddPlaylist.php
  lib/Routes/Course/CourseRemovePlaylist.php
Labels: type:bug, v:3, type:security

#1092 Allow users to watch videos in courseware blocks again
  courseware/vueapp/components/VideoRow.vue
  courseware/vueapp/courseware-plugin-opencast-video.vue
  lib/RouteMap.php
  lib/Routes/Opencast/UserRoles.php
  lib/Routes/Video/VideoShow.php
Labels: type:bug, v:3
