Repository elan-ev/studip-opencast-plugin, pull requests merged in 2024-02, with the labels that each got.

#922 Prevent reloading site when adding playlist
  vueapp/components/Playlists/PlaylistAddNewCard.vue
Labels: type:bug, v:3

#929 Load all playlists by default
  vueapp/store/playlists.module.js
Labels: type:bug, v:3

#932 Remove playlist link in playlists table
  vueapp/components/Playlists/PlaylistCard.vue
Labels: v:3, type:usability

#931 Fix missing default playlist when transferring course contents
  lib/Models/Helpers.php
  lib/Models/PlaylistSeminars.php
  lib/Routes/Video/VideoCopyToCourse.php
  vueapp/components/Videos/Actions/VideoCopyToSeminar.vue
  vueapp/store/videos.module.js
Labels: type:bug, v:3

#925 Fix major translations
  courseware/vueapp/components/CoursewareSearchBar.vue
  lib/Models/ScheduleHelper.php
  locale/en/LC_MESSAGES/opencast.mo
  locale/en/LC_MESSAGES/opencast.po
  vueapp/common/upload.service.js
  vueapp/components/Config/ConfigOption.vue
  vueapp/components/Config/EditServer.vue
  vueapp/components/Playlists/PlaylistEditCard.vue
  vueapp/components/Schedule/ScheduleList.vue
  vueapp/components/SearchBar.vue
  vueapp/components/UserCourseSelectable.vue
  vueapp/components/Videos/Actions/CaptionUpload.vue
  vueapp/components/Videos/Actions/VideoDelete.vue
  vueapp/components/Videos/Actions/VideoDeletePermanent.vue
  vueapp/components/Videos/Actions/VideoEdit.vue
  vueapp/components/Videos/Actions/VideoReport.vue
  vueapp/components/Videos/BulkActions/VideoDelete.vue
  vueapp/components/Videos/BulkActions/VideoRestore.vue
  vueapp/components/Videos/VideoFilePreview.vue
  vueapp/components/Videos/VideoUpload.vue
  vueapp/components/Videos/VideosSidebar.vue
  vueapp/components/ViewSwitch.vue
  vueapp/i18n/translations.json
  vueapp/views/Playlists.vue
Labels: type:bug, v:3

#933 DB Optimizations
  lib/Models/Playlists.php
  lib/Models/Videos.php
  lib/Routes/Course/CourseVideoList.php
  lib/Routes/Playlist/PlaylistVideoList.php
  lib/Routes/Video/VideoList.php
  migrations/073_add_event_state.php
  migrations/076_add_course_date_fields_for_events.php
  migrations/081_add_config_active.php
  migrations/090_optimize_db.php
Labels: type:enhancement, type:bug, v:3

#935 Focus on title input in create playlist dialog
  vueapp/components/Playlists/PlaylistAddNewCard.vue
Labels: v:3, type:usability

#930 Show first copied playlist as default playlist
  lib/Routes/Course/CourseListPlaylist.php
  lib/Routes/Playlist/PlaylistCopy.php
  vueapp/components/Playlists/PlaylistAddCard.vue
  vueapp/components/Playlists/PlaylistsCopyCard.vue
  vueapp/store/playlists.module.js
Labels: type:bug, v:3
