Repository elan-ev/studip-opencast-plugin, pull requests merged in 2024-01, with the labels that each got.

#865 Add videos from other courses to the course, close #761
  lib/Models/PlaylistSeminars.php
  lib/Models/Playlists.php
  lib/Models/Tags.php
  lib/Models/Videos.php
  lib/RouteMap.php
  lib/Routes/Course/CourseVideoList.php
  lib/Routes/Playlist/Authority.php
  lib/Routes/Tags/TagListForCourseVideos.php
  vueapp/components/Playlists/PlaylistAddToCourseDialog.vue
  vueapp/components/Playlists/PlaylistAddVideos.vue
  vueapp/components/UserCourseSelectable.vue
  vueapp/components/Videos/Actions/VideoCopyToSeminar.vue
  vueapp/components/Videos/VideosAddFromCourses.vue
  vueapp/components/Videos/VideosTable.vue
  vueapp/store/videos.module.js
Labels: v:3, type:usability

#869 Fix reference error in Verknüpfte Kurse
  vueapp/components/Playlists/PlaylistAddToCourseDialog.vue
Labels: type:bug, v:3

#871 Reload playlists properly and fix message updating
  vueapp/components/Playlists/PlaylistsTable.vue
  vueapp/store/messages.module.js
Labels: type:bug, v:3

#896 Remove Error component, MessageList will handle these
  vueapp/App.vue
  vueapp/app.js
  vueapp/components/Config/EditServer.vue
  vueapp/components/MessageList.vue
  vueapp/components/Videos/Actions/CaptionUpload.vue
  vueapp/components/Videos/VideoUpload.vue
  vueapp/store/error.module.js
  vueapp/store/index.js
  vueapp/store/messages.module.js
Labels: type:bug, v:3

#898 Fix currectVideo and dont play Video via VideoCard
  courseware/vueapp/components/LtiAuth.vue
  courseware/vueapp/components/VideoRow.vue
  courseware/vueapp/courseware-plugin-opencast-video.vue
Labels: type:bug, v:3

#897 Change icon of subtitle file select button
  vueapp/components/Videos/Actions/CaptionUpload.vue
Labels: v:3, type:visual-clarity

#900 Remove delete action for videos in courses,
  vueapp/components/Videos/VideoRow.vue
  vueapp/components/Videos/VideosTable.vue
Labels: v:3, type:usability

#894 Remove link from upload legal info
  migrations/084_upload_legal_info_remove_link.php
Labels: v:3, type:usability

#908 Fix migration version conflict
  migrations/085_upload_legal_info_remove_link.php
Labels: type:bug, v:3

#889 Show courses in video link to playliststs dialog
  lib/Models/PlaylistSeminars.php
  vueapp/components/UserPlaylistSelectable.vue
  vueapp/components/Videos/Actions/VideoLinkToPlaylists.vue
  vueapp/store/playlists.module.js
Labels: v:3, type:usability

#905 Show warning with the effects of editing a video
  vueapp/components/Videos/Actions/CaptionUpload.vue
  vueapp/components/Videos/Actions/VideoCut.vue
  vueapp/components/Videos/Actions/VideoDelete.vue
  vueapp/components/Videos/Actions/VideoEdit.vue
  vueapp/components/Videos/Actions/VideoLinkToPlaylists.vue
  vueapp/components/Videos/Actions/VideoRestore.vue
  vueapp/components/Videos/VideoChangeWarning.vue
  vueapp/components/Videos/VideoPlaylists.vue
  vueapp/components/Videos/VideoRow.vue
  vueapp/components/Videos/VideosTable.vue
Labels: type:enhancement, v:3

#906 Fix videos table of playlist loads all course videos
  vueapp/views/CoursesVideos.vue
Labels: type:bug, v:3, status:conflicts

#907 Wording of transfer course content action
  vueapp/components/Courses/CoursesSidebar.vue
Labels: v:3, type:visual-clarity

#916 Remove admin rights in acl on upload
  vueapp/common/upload.service.js
  vueapp/components/Videos/VideoUpload.vue
Labels: v:3, type:security

#917 Show correct time in upload dialog
  vueapp/components/Videos/VideoUpload.vue
Labels: type:bug, v:3

#919 Responsive Navigation items
  OpenCast.class.php
  app/controllers/course.php
  vueapp/components/Courses/CoursesSidebar.vue
Labels: type:bug, v:3

#895 Display no ghost video rows
  vueapp/components/Videos/VideosTable.vue
Labels: v:3, type:visual-clarity

#921 Problem loading videos in Workspace by Admin
  lib/Models/PlaylistSeminars.php
  lib/Models/Tags.php
  lib/Models/Videos.php
Labels: type:bug, v:3

#924 Problem with Default Playlist change in a course
  lib/Routes/Course/CourseAddPlaylist.php
  vueapp/components/Playlists/PlaylistsLinkCard.vue
Labels: v:3, type:usability
