Repository elan-ev/studip-opencast-plugin, pull requests merged in 2024-12, with the labels that each got.

#1097 Add github action workflow for tests and playlist acl tests
  .github/docker/docker-compose.opencast.yml
  .github/docker/docker-compose.studip.yml
  .github/docker/docker-compose.yml
  .github/docker/oc.sql
  .github/docker/opencast/etc/nginx/nginx.conf
  .github/docker/opencast/etc/opencast/org.opencastproject.kernel.security.OAuthConsumerDetailsService.cfg
  .github/docker/opencast/etc/opencast/org.opencastproject.plugin.impl.PluginManagerImpl.cfg
  .github/docker/opencast/etc/opencast/org.opencastproject.security.lti.LtiLaunchAuthenticationHandler.cfg
  .github/docker/opencast/etc/opencast/org.opencastproject.userdirectory.studip-default.cfg
  .github/docker/opencast/etc/opencast/security/mh_default_org.xml
  .github/workflows/run-tests.yml
  codeception.yml
  composer.json
  composer.lock
  courseware/devbuild.sh
  courseware/package.json
  lib/Models/PlaylistSeminars.php
  lib/Models/Playlists.php
  lib/Models/Videos.php
  lib/Routes/Course/CourseListForPlaylistVideos.php
  lib/Routes/Course/CourseListPlaylist.php
  lib/Routes/Playlist/PlaylistVideoList.php
  lib/Routes/Tags/TagListForPlaylistVideos.php
  lib/Routes/Video/VideoAdd.php
  package.json
  tests/.env
  tests/AclCest.php
  tests/CoursesCest.php
  tests/PlaylistsCest.php
  tests/UsersCest.php
  tests/_support/Helper/Api.php
Labels: type:tests

#1098 Update playlist in opencast when changing metadata
  lib/Models/Playlists.php
Labels: type:bug, v:3

#1099 Ansible: Set correct id in workflow config
  tools/ansible-testsystem/studip-demo/roles/cleaner/templates/oc.sql
Labels: type:bug, v:3

#1101 Courseware: Add loading spinner and speed up
  app/views/redirect/perform.php
  assets/css/opencast.scss
  courseware/vueapp/components/CoursewareVideoTable.vue
  courseware/vueapp/courseware-plugin-opencast-video.vue
Labels: type:enhancement

#1104 fixes #1093
  courseware/vueapp/courseware-plugin-opencast-video.vue
  locale/en/LC_MESSAGES/opencast.mo
  locale/en/LC_MESSAGES/opencast.po
  vueapp/components/Videos/Actions/VideoEdit.vue
  vueapp/components/Videos/VideoUpload.vue
  vueapp/i18n/translations.json
Labels: type:enhancement, v:3

#1106 Add version information to oc_videos and act upon it, fixes #1094
  cronjobs/opencast_discover_videos.php
  cronjobs/opencast_worker.php
  migrations/098_add_archive_version.php
Labels: type:bug, v:3

#1107 fixes #1080, remove non working link
  vueapp/components/Videos/VideoPlaylists.vue
Labels: type:bug, v:3

#1105 Add video tests
  codeception.yml
  composer.json
  tests/.env
  tests/AclCest.php
  tests/CoursesCest.php
  tests/PlaylistsCest.php
  tests/VideoCest.php
  tests/_data/test-with-audio.mp4
  tests/_support/Helper/Api.php
Labels: type:enhancement, v:3

#1108 Tests: Add fixes and refactorings
  tests/VideoCest.php
  tests/_support/Helper/Api.php
Labels: type:bug, v:3
