Repository elan-ev/studip-opencast-plugin, pull requests merged in 2024-05, with the labels that each got.

#956 Add Editor-tool link in caption dialog
  vueapp/components/Videos/Actions/CaptionUpload.vue
  vueapp/components/Videos/VideoRow.vue
Labels: type:enhancement, v:3

#955 Add Opencast Playlists
  cronjobs/opencast_sync_playlists.php
  lib/Models/Config.php
  lib/Models/Playlists.php
  lib/Models/PlaylistsUserPerms.php
  lib/Models/REST/ApiPlaylistsClient.php
  lib/Models/REST/RestClient.php
  lib/Providers/OpencastConstants.php
  lib/RouteMap.php
  lib/Routes/Config/ConfigAdd.php
  lib/Routes/Config/ConfigEdit.php
  lib/Routes/Config/SimpleConfigList.php
  lib/Routes/Opencast/UserRoles.php
  lib/Routes/Playlist/PlaylistAdd.php
  lib/Routes/Playlist/PlaylistAddVideo.php
  lib/Routes/Playlist/PlaylistRemoveVideo.php
  lib/Routes/Playlist/PlaylistShow.php
  lib/Routes/Playlist/PlaylistUpdate.php
  lib/Routes/Playlist/PlaylistUpdatePositions.php
  lib/Routes/Video/VideoAddToPlaylist.php
  lib/Routes/Video/VideoCopyToCourse.php
  migrations/092_add_oc_playlists.php
  vueapp/common/datetime.filter.js
  vueapp/components/Config/ServerCard.vue
  vueapp/components/Courses/CoursesSidebar.vue
  vueapp/components/LtiAuth.vue
  vueapp/components/Playlists/PlaylistAddNewCard.vue
  vueapp/components/Playlists/PlaylistCard.vue
  vueapp/components/Playlists/PlaylistsCopyCard.vue
  vueapp/components/Playlists/PlaylistsTable.vue
  vueapp/components/Videos/Actions/VideoAddToPlaylist.vue
  vueapp/components/Videos/Actions/VideoLinkToPlaylists.vue
  vueapp/components/Videos/VideoUpload.vue
  vueapp/components/Videos/VideosAddFromContents.vue
  vueapp/components/Videos/VideosAddFromCourses.vue
  vueapp/components/Videos/VideosTable.vue
  vueapp/store/config.module.js
  vueapp/store/opencast.module.js
  vueapp/store/playlists.module.js
  vueapp/store/videos.module.js
  vueapp/views/CoursesVideos.vue
Labels: v:3, status:conflicts, type:feature

#972 Remove unused stuff
  lib/Models/REST/AdminNgEventClient.php
  lib/Models/REST/ApiEventsClient.php
  lib/Models/REST/ApiWorkflowsClient.php
  lib/Models/REST/IngestClient.php
  lib/Models/REST/WorkflowClient.php
  lib/Models/Videos.php
  lib/VersionHelper.php
  lib/Versions/4.6/OCCourseModel.php
  lib/Versions/4.6/SearchClient.php
Labels: priority:low, type:infrastructure

#971 Speed up playlist actions
  lib/RouteMap.php
  lib/Routes/Playlist/PlaylistAddVideo.php
  lib/Routes/Playlist/PlaylistAddVideos.php
  lib/Routes/Playlist/PlaylistRemoveVideo.php
  lib/Routes/Playlist/PlaylistRemoveVideos.php
  vueapp/common/api.service.js
  vueapp/components/Videos/VideosTable.vue
  vueapp/store/playlists.module.js
Labels: type:enhancement, v:3

#973 Issue 902
  lib/Models/VideosUserPerms.php
  lib/RouteMap.php
  lib/Routes/Playlist/Authority.php
  lib/Routes/Playlist/PlaylistAddVideos.php
  lib/Routes/Playlist/PlaylistRemoveVideos.php
  lib/Routes/Video/VideoAdd.php
  lib/Routes/Video/VideoSharesList.php
  lib/Routes/Video/VideoSharesUpdate.php
  vueapp/common/api.service.js
  vueapp/components/Playlists/PlaylistAddVideos.vue
  vueapp/components/Videos/Actions/VideoAccess.vue
  vueapp/components/Videos/Actions/VideoLinkToPlaylists.vue
  vueapp/components/Videos/Actions/VideoRemoveFromPlaylist.vue
  vueapp/components/Videos/VideoRow.vue
  vueapp/components/Videos/VideoUpload.vue
  vueapp/components/Videos/VideosAddFromContents.vue
  vueapp/components/Videos/VideosAddFromCourses.vue
  vueapp/components/Videos/VideosTable.vue
  vueapp/store/playlists.module.js
  vueapp/store/videos.module.js
  vueapp/views/CoursesVideos.vue
Labels: type:bug, v:3
