Repository elan-ev/studip-opencast-plugin, pull requests merged in 2024-06, with the labels that each got.

#975 Allow public videos in oc and ui to easily retrieve video urls
  assets/css/opencast.scss
  courseware/vueapp/components/VideoRow.vue
  courseware/vueapp/courseware-plugin-opencast-video.vue
  cronjobs/opencast_discover_videos.php
  lib/Helpers/PlaylistMigration.php
  lib/Models/Playlists.php
  lib/Models/REST/ApiEventsClient.php
  lib/Models/REST/RestClient.php
  lib/Models/Videos.php
  lib/Providers/Perm.php
  lib/RouteMap.php
  lib/Routes/Config/ConfigList.php
  lib/Routes/Config/ConfigMigratePlaylists.php
  lib/Routes/Playlist/PlaylistAddToCourse.php
  lib/Routes/Playlist/PlaylistAddVideos.php
  lib/Routes/Playlist/PlaylistRemoveVideos.php
  lib/Routes/Playlist/PlaylistUpdatePositions.php
  lib/Routes/Playlist/PlaylistVideoList.php
  locale/en/LC_MESSAGES/opencast.mo
  locale/en/LC_MESSAGES/opencast.po
  migrations/092_add_oc_playlists.php
  vueapp/components/Config/AdminConfigs.vue
  vueapp/components/Videos/Actions/VideoAccess.vue
  vueapp/components/Videos/Actions/VideoDownload.vue
  vueapp/components/Videos/Actions/VideoEdit.vue
  vueapp/components/Videos/VideoRow.vue
  vueapp/components/Videos/VideosTable.vue
  vueapp/i18n/translations.json
  vueapp/store/config.module.js
Labels: type:enhancement, v:3, v:3-ugoe

#958 Run workflow on caption upload
  INSTALL.md
  app/controllers/admin.php
  app/controllers/contents.php
  app/controllers/course.php
  lib/Models/Helpers.php
  lib/Models/WorkflowConfig.php
  lib/Routes/Config/SimpleConfigList.php
  migrations/093_add_subtitles_workflow.php
  vueapp/common/upload.service.js
  vueapp/components/Config/WorkflowOptions.vue
  vueapp/components/Videos/Actions/CaptionUpload.vue
  vueapp/components/Videos/VideoUpload.vue
Labels: type:enhancement, type:bug, v:3

#980 Set acls for videos, playlists and series
  cronjobs/opencast_sync_acls.php
  lib/Helpers/PlaylistMigration.php
  lib/Models/Helpers.php
  lib/Models/Playlists.php
  lib/Models/REST/SeriesClient.php
  lib/Models/REST/ServicesClient.php
  lib/Models/SeminarSeries.php
  lib/Models/Videos.php
  lib/Routes/Opencast/UserRoles.php
  migrations/094_add_acl_cronjob.php
Labels: type:enhancement, v:3
