Repository elan-ev/studip-opencast-plugin, pull requests merged in 2025-03, with the labels that each got.

#1239 Speed up video sync exist check in discover cronjob
  cronjobs/opencast_discover_videos.php
Labels: type:enhancement, v:3

#1249 Fix periodic execution times of cronjobs
  migrations/051_new_scheme_and_cronjobs.php
  migrations/094_add_acl_cronjob.php
Labels: type:bug, v:3

#1252 Fix faulty cronjob entries from v2
  migrations/051_new_scheme_and_cronjobs.php
Labels: type:bug, v:3

#1227 Fixes and updates the perms
  app/controllers/redirect.php
  lib/Models/Playlists.php
  lib/Models/Tags.php
  lib/Models/Videos.php
  lib/Routes/Course/CourseAddPlaylist.php
  lib/Routes/Playlist/Authority.php
  lib/Routes/Playlist/PlaylistAddVideos.php
  lib/Routes/Playlist/PlaylistRemoveVideos.php
  lib/Routes/Video/VideoDelete.php
  lib/Routes/Video/VideoReport.php
  lib/Routes/Video/VideoRestore.php
  lib/Routes/Video/VideoSharesList.php
  lib/Routes/Video/VideoSharesUpdate.php
  lib/Routes/Video/VideoShow.php
  lib/Routes/Video/VideoUpdate.php
  vueapp/components/Videos/VideoRow.vue
  vueapp/store/videos.module.js
Labels: type:enhancement, type:bug, v:3

#1228 Only add owner video perm to uploader or scheduler of the recording
  lib/Models/ScheduleHelper.php
  lib/Models/ScheduledRecordings.php
  lib/Models/VideosUserPerms.php
  lib/Routes/Video/VideoAdd.php
  migrations/102_add_user_to_scheduled_recordings.php
Labels: v:3, type:feature

#1230 Rework user videos
  courseware/vueapp/courseware-plugin-opencast-video.vue
  lib/Models/Videos.php
  lib/RouteMap.php
  lib/Routes/Courseware/CoursewareVideoList.php
  vueapp/components/Videos/VideosTable.vue
  vueapp/store/videos.module.js
Labels: type:enhancement, type:bug, v:3, type:usability

#1240 Show livestream bulk action only if schedule dates support livestream
  lib/Models/ScheduleHelper.php
  lib/Routes/Course/CourseListSchedule.php
  vueapp/components/Courses/CoursesSidebar.vue
  vueapp/components/Schedule/ScheduleList.vue
  vueapp/store/schedule.module.js
Labels: v:3, type:usability

#1232 Migrate OC invisibility and remove the deprecated functions
  OpencastV3.class.php
  lib/Models/SeminarSeries.php
  lib/Models/WidgetHelper.php
  lib/RouteMap.php
  lib/Routes/Course/CourseConfig.php
  lib/Routes/Course/CourseSetVisibility.php
  migrations/103_migrate_seminar_invisibility.php
  vueapp/components/Courses/CoursesSidebar.vue
  vueapp/store/opencast.module.js
Labels: type:enhancement, v:3

#1242 Courseware: Reset paging when searching for or sorting videos
  courseware/vueapp/courseware-plugin-opencast-video.vue
Labels: type:bug, v:3

#1247 Improve wording for target playlists
  vueapp/components/Courses/CoursesSidebar.vue
Labels: v:3, type:visual-clarity

#1248 Disable copy button during playlist copy process
  vueapp/components/Playlists/PlaylistsCopyCard.vue
Labels: type:bug, v:3

#1233 Add config option to allow users to assign permissions on videos
  lib/Providers/OpencastConstants.php
  lib/Routes/Video/VideoSharesUpdate.php
  migrations/104_config_option_permission_assignment.php
  vueapp/components/Videos/Actions/VideoAccess.vue
  vueapp/components/Videos/VideoRow.vue
Labels: v:3, type:feature

#1241 Show playlists from user's courses in copy dialog and in video filter
  lib/Models/Playlists.php
Labels: v:3, type:usability

#1213 Only clear relevant caches
  migrations/096_fix_v3.php
Labels: type:bug, v:3

#1253 Add missing playlist migration check
  lib/Models/Videos.php
Labels: type:bug, v:3

#1250 Add keyboard support for the common actions
  courseware/vueapp/components/VideoRow.vue
  vueapp/components/Courses/CoursesSidebar.vue
  vueapp/components/Videos/Actions/VideoAccess.vue
  vueapp/components/Videos/VideoRow.vue
  vueapp/components/Videos/VideosSidebar.vue
Labels: v:3, type:accessibility

#1215 Completely remove subtiltes workflow, Correctly update workflows if tags changed
  INSTALL.md
  lib/Models/Workflow.php
  lib/Models/WorkflowConfig.php
  migrations/105_remove_subtitles_workflow.php
  tools/ansible-testsystem/studip-demo/roles/cleaner/templates/oc.sql
  vueapp/components/Config/WorkflowOptions.vue
Labels: type:bug, v:3

#1263 Only check future scheduled recordings to prevent deleting old recorded events
  cronjobs/opencast_refresh_scheduling.php
Labels: type:bug, v:3

#1262 Make sure video tokens exist whem migrating courseware
  cronjobs/opencast_worker.php
  migrations/100_migrate_missing_cw_blocks.php
Labels: type:bug, v:3

#1289 Show clickable video title if no preview is available
  vueapp/components/Videos/VideoRow.vue
Labels: v:3, type:visual-clarity
