Repository elan-ev/studip-opencast-plugin, pull requests merged in 2025-04, with the labels that each got.

#1291 Hide videos not available in OC but don't delete them from Stud.IP DB
  cronjobs/opencast_discover_videos.php
  lib/Models/Videos.php
Labels: v:3, type:feature

#1290 Only change ROLE_ANONYMOUS in Opencast if explicitly set by user
  composer.lock
  lib/Models/Helpers.php
  lib/Models/REST/ApiEventsClient.php
  lib/Models/REST/RestClient.php
  lib/Models/Videos.php
  lib/RouteMap.php
  lib/Routes/Log/LogEntryCreate.php
  lib/Routes/Video/VideoWorldwideShareUpdate.php
  vueapp/components/Videos/Actions/VideoAccess.vue
  vueapp/components/Videos/VideoUpload.vue
  vueapp/store/index.js
  vueapp/store/log.module.js
  vueapp/store/videos.module.js
Labels: type:bug, v:3

#1294 Make sure video owners are notified
  lib/Models/Helpers.php
Labels: type:bug, v:3, priority:critical

#1299 Fix scheduling for devices with capabilities
  lib/Models/REST/IngestClient.php
Labels: type:bug, v:3

#1297 Scheduling permission improvements
  OpencastV3.class.php
  lib/Providers/Perm.php
  lib/Routes/Course/CourseConfig.php
  lib/Routes/Course/CourseListSchedule.php
  lib/Routes/Playlist/PlaylistScheduleUpdate.php
  lib/Routes/Schedule/ScheduleAdd.php
  lib/Routes/Schedule/ScheduleBulk.php
  lib/Routes/Schedule/ScheduleDelete.php
  lib/Routes/Schedule/ScheduleShow.php
  lib/Routes/Schedule/ScheduleUpdate.php
  vueapp/components/Courses/CoursesSidebar.vue
  vueapp/components/Schedule/ScheduleList.vue
Labels: type:bug, v:3, priority:critical

#1302 Correctly consider global default visibility of videos
  assets/css/opencast.scss
  lib/Models/Videos.php
  vueapp/components/Videos/VideoRow.vue
Labels: type:bug, v:3

#1309 prevent php warnings, fixes #1308
  lib/Models/REST/SeriesClient.php
  lib/Models/ScheduleHelper.php
Labels: type:bug, v:3

#1312 Correcting the server url fails
  lib/Models/Config.php
  lib/Models/REST/ServicesClient.php
  lib/RouteMap.php
  lib/Routes/Config/ConfigEdit.php
  lib/Routes/Config/ConfigSetActivation.php
  vueapp/components/Config/ServerCard.vue
  vueapp/store/config.module.js
Labels: type:bug, v:3

#1315 List correct institutes for admin, only list course with enabled opencast plugin
  lib/Routes/Opencast/UserRoles.php
Labels: type:bug, v:3

#1323 Remove html escaping in schedule title
  lib/Models/ScheduleHelper.php
Labels: type:bug, v:3

#1334 Show correct video duration
  lib/Models/Videos.php
Labels: type:bug

#1328 Fix notification bugs in "Video freigeben" dialog
  lib/Routes/Video/VideoWorldwideShareUpdate.php
  vueapp/components/Videos/Actions/VideoAccess.vue
Labels: type:bug

#1333 Fix exception in cw block when video is missing
  app/controllers/redirect.php
Labels: type:bug, v:3

#1338 Correctly show an error message when uploading a video
  vueapp/common/upload.service.js
Labels: type:bug, v:3

#1340 Reduce user roles to pevent errors in Opencast
  lib/Routes/Opencast/UserRoles.php
Labels: type:bug, v:3

#1337 Transfer the value of OPENCAST_ALLOW_MEDIADOWNLOAD config to OPENCAST_MEDIADOWNLOAD
  migrations/062_add_config_custom_download.php
Labels: type:bug, v:3, priority:medium

#1331 Fix cw block copy mapping
  cronjobs/opencast_courseware_block_copy_mapping.php
  lib/BlockTypes/OpencastBlockV3.php
Labels: type:bug, v:3

#1324 Course Default Visibility feature
  lib/Models/Videos.php
  lib/RouteMap.php
  lib/Routes/Course/CourseConfig.php
  lib/Routes/Course/CourseSetDefaultVideosVisibility.php
  migrations/109_add_course_config_default_visibility.php
  vueapp/components/Courses/CoursesSidebar.vue
  vueapp/components/Courses/EpisodesDefaultVisibilityDialog.vue
  vueapp/components/Videos/VideoRow.vue
  vueapp/store/opencast.module.js
  vueapp/store/videos.module.js
  vueapp/views/Course.vue
Labels: v:3, type:feature

#1310 Surgically remove course content transfer feature "Kursinhalte übertragen
  lib/RouteMap.php
  lib/Routes/Video/VideoCopyToCourse.php
  vueapp/components/Courses/CoursesSidebar.vue
  vueapp/components/Videos/Actions/VideoCopyToSeminar.vue
  vueapp/components/Videos/VideosTable.vue
  vueapp/store/videos.module.js
  vueapp/views/Course.vue
Labels: v:3, type:feature, type:usability

#1342 Fix and review for the hardcoded permission checks in API Routes and UI
  lib/Models/Tags.php
  lib/Providers/Perm.php
  lib/Routes/Course/CourseConfig.php
  lib/Routes/Course/CourseListForPlaylistVideos.php
  lib/Routes/Course/CourseSetUpload.php
  lib/Routes/Playlist/Authority.php
  lib/Routes/Playlist/PlaylistAddToCourse.php
  lib/Routes/Playlist/PlaylistCopy.php
  lib/Routes/Playlist/PlaylistVideoList.php
  lib/Routes/Tags/TagListForPlaylistVideos.php
  vueapp/components/Playlists/PlaylistAddVideos.vue
  vueapp/components/Videos/VideoRow.vue
  vueapp/components/Videos/VideosTable.vue
  vueapp/views/Course.vue
Labels: type:bug, v:3

#1343 Update elan-ev/opencast-api to 1.9.1
  composer.json
  composer.lock
Labels: type:bug

#1344 Add bulk action to move videos to trash in workspace
  vueapp/components/Videos/VideosTable.vue
Labels: v:3, type:feature

#1346 Fix allow media download action
  lib/Models/PlaylistSeminars.php
  vueapp/components/Courses/CoursesSidebar.vue
  vueapp/components/Videos/VideosTable.vue
  vueapp/store/playlists.module.js
Labels: type:bug, v:3

#1355 Video embedding code
  assets/css/opencast.scss
  lib/Routes/Config/SimpleConfigList.php
  vueapp/components/Videos/Actions/VideoAccess.vue
  vueapp/components/Videos/Actions/VideoEmbeddingCode.vue
  vueapp/components/Videos/VideoRow.vue
  vueapp/components/Videos/VideosTable.vue
Labels: type:feature
