Repository elan-ev/studip-opencast-plugin, pull requests merged in 2025-02, with the labels that each got.

#1132 Show course videos in cw
  assets/css/courseware.scss
  courseware/vueapp/components/CoursewareSearchBar.vue
  courseware/vueapp/courseware-plugin-opencast-video.vue
  lib/Models/Videos.php
Labels: type:bug, v:3, type:usability

#1169 Fix `Integrity constraint violation` when adding videos to courses without playlist via cronjob
  lib/Models/Helpers.php
Labels: type:bug, v:3

#1173 Allow deletion of faulty video entries in Stud.IP
  cronjobs/opencast_clear_recycle_bin.php
  lib/Models/REST/ApiEventsClient.php
  lib/Models/Videos.php
Labels: type:bug, v:3

#1174 Unify character sets and collations in migrations
  migrations/001_init_ocplugin.php
  migrations/002_workflow_storage.php
  migrations/008_workflow_configuration.php
  migrations/022_add_tos.php
  migrations/042_remove_oc_seminar_workflows.php
  migrations/051_new_scheme_and_cronjobs.php
  migrations/053_new_courseware_block.php
  migrations/059_add_linkshare_table.php
  migrations/061_update_workflow_tables.php
  migrations/064_alter_linkshare_table.php
  migrations/066_update_workflow_tables_two.php
  migrations/072_add_user_series.php
  migrations/075_remove_editor_workflow_config.php
  migrations/077_update_cw_block.php
  migrations/093_add_subtitles_workflow.php
Labels: type:enhancement, v:3

#1176 Allow Stud.IP internal sharing, even if global sharing is disabled
  lib/Routes/Video/VideoSharesList.php
  lib/Routes/Video/VideoSharesUpdate.php
  vueapp/components/Videos/Actions/VideoAccess.vue
Labels: type:bug, v:3

#1177 Do not show missing default course playlist if the config is not available yet
  vueapp/views/CoursesVideos.vue
Labels: type:bug, v:3

#1183 Try some caching for tests
  .github/docker/docker-compose-cache.json
  .github/workflows/run-tests.yml
Labels: type:tests

#1178 Update video acls in oc when adding to new course
  courseware/vueapp/components/VideoRow.vue
  cronjobs/opencast_discover_videos.php
  cronjobs/opencast_worker.php
  lib/Models/PlaylistVideos.php
  lib/Models/Playlists.php
  lib/Models/Videos.php
  lib/Routes/Playlist/PlaylistAddVideos.php
  lib/Routes/Playlist/PlaylistRemoveVideos.php
  migrations/099_add_playlist_availability.php
  tests/VideoCest.php
  vueapp/components/Videos/VideoRow.vue
Labels: type:bug, v:3

#1180 Add server setting for role based event access
  INSTALL.md
  lib/Models/Config.php
  lib/Models/Videos.php
  vueapp/components/Config/EditServer.vue
Labels: v:3, type:feature

#1181 Remove oc playlist migration in db migrations
  migrations/092_add_oc_playlists.php
Labels: v:3, type:feature

#1199 Add videos added to a playlist in Stud.IP to OC as well when added by cronjob
  lib/Models/Playlists.php
  lib/Models/Videos.php
  lib/Routes/Playlist/PlaylistAddVideos.php
  lib/Routes/Playlist/PlaylistRemoveVideos.php
  migrations/099_add_playlist_availability.php
Labels: type:bug, v:3

#1188 Fix payload of cw blocks and migrate blocks to oc_video_cw_blocks
  migrations/100_migrate_missing_cw_blocks.php
Labels: type:bug, v:3

#1203 Add default playlist to Opencast
  lib/Models/Helpers.php
Labels: type:bug, v:3

#1207 Fix broken text filter in videos table
  lib/Models/Videos.php
Labels: type:bug, v:3

#1208 Show no scheduled recordings in the videos table
  cronjobs/opencast_discover_videos.php
Labels: type:bug, v:3

#1200 Correct handling of metadata from Opencast and storing it back
  courseware/vueapp/components/CoursewareVideoTable.vue
  courseware/vueapp/components/VideoRow.vue
  lib/Models/Videos.php
  lib/Routes/Video/VideoUpdate.php
  locale/en/LC_MESSAGES/opencast.mo
  locale/en/LC_MESSAGES/opencast.po
  vueapp/components/Videos/Actions/VideoEdit.vue
  vueapp/components/Videos/VideoFilePreview.vue
  vueapp/components/Videos/VideoRow.vue
  vueapp/components/Videos/VideoUpload.vue
  vueapp/components/Videos/VideosTable.vue
  vueapp/i18n/translations.json
Labels: type:bug, v:3

#1210 Update check-label.yml
  .github/workflows/check-label.yml
Labels: v:3

#1209 Correct texts, fix translations
  OpencastV3.class.php
  README.md
  assets/javascript/oc46.js
  courseware/vueapp/components/VideoRow.vue
  courseware/vueapp/courseware-plugin-opencast-video.vue
  cronjobs/opencast_clear_recycle_bin.php
  lib/Models/Config.php
  lib/Models/Resources.php
  lib/Models/ScheduledRecordings.php
  lib/Routes/Video/VideoRestore.php
  locale/en/LC_MESSAGES/opencast.mo
  locale/en/LC_MESSAGES/opencast.po
  migrations/022_add_tos.php
  migrations/034_update_tos.php
  vueapp/components/Config/EditServer.vue
  vueapp/components/Config/ServerCard.vue
  vueapp/components/Playlists/PlaylistAddToCourseDialog.vue
  vueapp/components/Playlists/PlaylistsTable.vue
  vueapp/components/Schedule/ScheduleList.vue
  vueapp/components/TagBar.vue
  vueapp/components/Videos/Actions/VideoAccess.vue
  vueapp/components/Videos/Actions/VideoCopyToSeminar.vue
  vueapp/components/Videos/Actions/VideoLinkToPlaylists.vue
  vueapp/components/Videos/Actions/VideoRestore.vue
  vueapp/components/Videos/BulkActions/VideoRestore.vue
  vueapp/components/Videos/VideoRow.vue
  vueapp/components/Videos/VideoUpload.vue
  vueapp/i18n/translations.json
  vueapp/views/CoursesVideos.vue
Labels: v:3, type:translation

#1212 Add separate config options for sharing, public sharing and technical feedback
  lib/Models/Videos.php
  lib/Providers/OpencastConstants.php
  lib/Routes/Video/VideoReport.php
  lib/Routes/Video/VideoSharesList.php
  lib/Routes/Video/VideoSharesUpdate.php
  migrations/097_update_sharing_option.php
  migrations/101_config_options_features.php
  vueapp/components/Config/GlobalOptions.vue
  vueapp/components/Videos/Actions/VideoAccess.vue
  vueapp/components/Videos/VideoRow.vue
Labels: v:3, type:feature

#1214 Remove broken lti check
  vueapp/components/Config/EditServer.vue
Labels: type:bug, v:3

#1202 Remove subtitle lti roles in INSTALL.md
  INSTALL.md
Labels: v:3, type:documentation
