Repository elan-ev/studip-opencast-plugin, pull requests merged in 2025-01, with the labels that each got.

#1121 Delete course playlist completely
  lib/Routes/Course/CourseRemovePlaylist.php
  vueapp/components/Videos/VideosTable.vue
Labels: type:feature

#1124 Add episode id roles to user provider
  lib/Routes/Opencast/UserRoles.php
Labels: type:enhancement, v:3

#1122 Fix overlapping of playlist dialog by Stud.IP header
  vueapp/components/Courses/CoursesSidebar.vue
  vueapp/views/Course.vue
Labels: type:bug, v:3, type:visual-clarity

#1126 Tests: Cleanup and temporarly disable course roles checks
  .github/docker/docker-compose.opencast.yml
  .github/docker/docker-compose.studip.yml
  .github/docker/oc.sql
  tests/VideoCest.php
Labels: v:3, type:tests

#1128 Fix broken playlist visibility
  vueapp/components/Courses/CoursesSidebar.vue
  vueapp/components/Playlists/PlaylistCard.vue
  vueapp/components/Playlists/PlaylistsCopyCard.vue
  vueapp/views/CoursesVideos.vue
Labels: type:bug, v:3

#1129 Don't rename playlist to "Kurswiedergabeliste" after update
  lib/Routes/Course/CourseUpdatePlaylist.php
Labels: type:bug, v:3

#1125 Fix series check during scheduling
  lib/Models/SeminarSeries.php
Labels: type:bug, v:3

#1130 Fix node script build-dev
  courseware/package.json
Labels: type:bug, v:3

#1131 Fix missing videos with read perm in cw block
  courseware/vueapp/components/VideoRow.vue
Labels: type:bug, v:3

#1155 Show notification when video is ready
  bootstrap.php
  cronjobs/opencast_worker.php
  lib/Models/Helpers.php
Labels: type:bug, v:3

#1156 Prevent mixing of mp4 and webm
  vueapp/components/Videos/VideoUpload.vue
Labels: type:bug, v:3

#1141 Allow downloading of media files
  OpencastV3.class.php
  app/controllers/redirect.php
  lib/Models/Videos.php
  lib/Routes/Playlist/PlaylistRemoveVideos.php
  package-lock.json
  vueapp/components/Videos/Actions/CaptionUpload.vue
  vueapp/components/Videos/Actions/VideoAccess.vue
  vueapp/components/Videos/Actions/VideoCut.vue
  vueapp/components/Videos/Actions/VideoDownload.vue
  vueapp/components/Videos/VideosTable.vue
  vueapp/store/playlists.module.js
  vueapp/templates/admin_index.php
  vueapp/templates/contents_index.php
  vueapp/templates/course_index.php
Labels: type:bug, v:3
