Repository elan-ev/studip-opencast-plugin, pull requests merged in 2025-05, with the labels that each got.

#1358 Show and log video upload errors
  vueapp/common/upload.service.js
Labels: type:enhancement, v:3

#1349 New Download Process
  app/controllers/redirect.php
  assets/css/opencast.scss
  lib/Models/REST/RestClient.php
  vueapp/app.js
  vueapp/components/ProgressBar.vue
  vueapp/components/Studip/StudipDialog.vue
  vueapp/components/Videos/Actions/VideoDownload.vue
Labels: type:enhancement, v:3, priority:high

#1356 Enhance video public sharing functionality
  lib/Routes/Video/VideoWorldwideShareUpdate.php
  vueapp/components/Videos/Actions/VideoAccess.vue
  vueapp/components/Videos/VideoRow.vue
Labels: type:bug, v:3, priority:low

#1360 Reduce user roles by using course roles
  lib/Routes/Opencast/UserRoles.php
Labels: type:enhancement, type:bug, v:3

#1368 Tests: Fail curl command on error
  .github/workflows/run-tests.yml
Labels: type:bug, v:3

#1375 Add embedding link
  assets/css/opencast.scss
  vueapp/components/Videos/Actions/VideoAccess.vue
  vueapp/components/Videos/Actions/VideoEmbeddingCode.vue
  vueapp/components/Videos/VideoRow.vue
Labels: type:enhancement, v:3

#1364 Add check for services in maintenance mode
  lib/Models/REST/Config.php
Labels: type:bug, v:3

#1370 Fix memory limit overflow in sync acls cronjob
  cronjobs/opencast_sync_acls.php
Labels: type:bug, v:3

#1369 Handle null episode in check event acl
  lib/Models/Videos.php
Labels: type:bug, v:3

#1379 validate opencast version number
  vueapp/components/Config/EditServer.vue
  vueapp/components/Config/ServerCard.vue
Labels: type:visual-clarity

#1367 Remove block copy mapping
  cronjobs/opencast_courseware_block_copy_mapping.php
  lib/BlockTypes/OpencastBlockV3.php
  lib/Models/CoursewareBlockMappings.php
  lib/Models/VideoCoursewareBlocks.php
  lib/Routes/Opencast/UserRoles.php
  lib/Versions/5.x/OpencastBlockV3.php
  migrations/111_remove_cw_block_copy_mapping.php
Labels: type:enhancement, v:3

#1378 use studip loading indicator
  assets/css/opencast.scss
  courseware/vueapp/components/CoursewareVideoTable.vue
  courseware/vueapp/components/StudipProgressIndicator.vue
  vueapp/components/Studip/StudipProgressIndicator.vue
  vueapp/components/Videos/EmptyVideoRow.vue
  vueapp/components/Videos/VideosTable.vue
Labels: type:visual-clarity
